### PR TITLE
add Buffer to decode bench

### PR DESCRIPTION
**Pull request by ronag**
Interesting to compare with `toString`.

### CODE REVIEW

**Review by anonrig — CHANGES_REQUESTED** [review]
Can you also add the changes to `text-decoder/deno.js` file?

**Comment by anonrig** [comment]
It has. Here's an example of a import statement for Buffer. https://github.com/anonrig/node-benchmarks/blob/main/text-encoder/deno.js#L2

**Comment by ronag** [comment]
Done

**Comment by anonrig** [comment]
```
> node-benchmarks@1.0.0 text-decoder
> ~/Developer/node/out/Release/node ./text-decoder/index.mjs && bun run ./text-decoder/index.mjs && deno run -A ./text-decoder/deno.js

cpu: Apple M1 Max
runtime: node v20.0.0-pre (arm64-darwin)

benchmark                              time (avg)             (min … max)       p75       p99      p995
------------------------------------------------------------------------- -----------------------------
smallUint8 - TextDecoder.decode()  310.12 ns/iter (298.67 ns … 337.68 ns)  313.9 ns 332.39 ns 337.68 ns
bigUint8 - TextDecoder.decode()      2.64 µs/iter     (2.58 µs … 2.81 µs)   2.65 µs   2.81 µs   2.81 µs
smallUint8 - buffer.toString()     310.94 ns/iter (301.33 ns … 323.12 ns)  313.3 ns  320.4 ns 323.12 ns
bigUint8 - buffer.toString()         2.61 µs/iter     (2.58 µs … 2.67 µs)   2.61 µs   2.67 µs   2.67 µs
cpu: Apple M1 Max
runtime: bun 0.2.2 (arm64-darwin)

benchmark                              time (avg)             (min … max)       p75       p99      p995
------------------------------------------------------------------------- -----------------------------
smallUint8 - TextDecoder.decode()  213.42 ns/iter (198.34 ns … 363.18 ns) 215.38 ns 223.33 ns 223.95 ns
bigUint8 - TextDecoder.decode()      1.17 µs/iter     (1.03 µs … 1.39 µs)   1.19 µs   1.39 µs   1.39 µs
smallUint8 - buffer.toString()     209.47 ns/iter (197.97 ns … 312.25 ns) 210.43 ns 219.59 ns 257.02 ns
bigUint8 - buffer.toString()         1.18 µs/iter     (1.06 µs … 1.27 µs)   1.22 µs   1.27 µs   1.27 µs
cpu: Apple M1 Max
runtime: deno 1.27.2 (aarch64-apple-darwin)

benchmark                              time (avg)             (min … max)       p75       p99      p995
------------------------------------------------------------------------- -----------------------------
smallUint8 - TextDecoder.decode()  457.18 ns/iter (440.16 ns … 475.82 ns) 461.89 ns 471.85 ns 475.82 ns
bigUint8 - TextDecoder.decode()      3.57 µs/iter     (3.54 µs … 3.69 µs)   3.58 µs   3.69 µs   3.69 µs
smallUint8 - buffer.toString()     388.51 ns/iter (381.32 ns … 406.67 ns) 389.91 ns 405.69 ns 406.67 ns
bigUint8 - buffer.toString()        57.32 µs/iter  (51.63 µs … 267.33 µs)  55.63 µs 118.58 µs 127.54 µs```

**Comment by ronag** [comment]
Looks pretty equal. Nice!

**Comment by anonrig** [comment]
It's not a 1-to-1 comparison, since `Buffer.from(uint8array)` is not in the benchmark, but yes they're quite identical.

**Comment by ronag** [comment]
The only perf issue with text decoder now is the case when slicing, i.e.

```js
decoder.decode(buf.subarray(10, 32))
buf.toString(null, 10, 32)
```

**Comment by anonrig** [comment]
Unfortunately TextDecoder spec does not include lower & upper bounds for slicing https://developer.mozilla.org/en-US/docs/Web/API/TextDecoder/decode

**Pull request merged**
